# fly.toml app configuration file generated for neirea-portfolio on 2025-04-05T16:39:06+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'neirea-portfolio'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
