name: Fly Deploy
on:
    push:
        branches:
            - main
        paths:
            - ".github/**"
            - "server/**"

defaults:
    run:
        working-directory: ./server
jobs:
    test:
        name: Running tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm ci
            - run: npm run test
    deploy:
        needs: test
        name: Deploy app
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - run: flyctl deploy --remote-only
        env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
